from_latest_tag = true
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = true
skip_ci = "[skip ci]"
skip_untracked = true
tag_prefix = "v"

branch_whitelist = ["main"]

pre_bump_hooks = []
post_bump_hooks = []

generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
pre_package_bump_hooks = []
post_package_bump_hooks = []

[packages]
pdm-bump-scm = { path = "src/plugins/pdm-bump-scm" }
pdm-build-monorepo = { path = "src/plugins/pdm-build-monorepo" }

[commit_types]
# feat, fix, build, ci, revert, docs, test, style, chore, perf
hotfix = { changelog_title = "Hotfixes" }
security = { changelog_title = "Security" }
# Omit commits from changelog
chore = { changelog_title = "", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = [{ username = "gravures", signature = "Gilles Coissac" }]
remote = "github.com"
repository = "pdm-devhelp"
owner = "gravures"

[bump_profiles]
[git_hooks]
